### ISSUE TITLE
Properly document the code

### ISSUE THREAD

**Issue by barbaradanzo** [barbaradanzo/birthdays#4]
Properly document the code

**Comment by xuelanli** [comment]
document_code fixed https://github.com/barbaradanzo/birthdays/commit/ffb6341e99e3e0a0a84dbbbacbbc1a5fd6ca09ae

**Comment by xuelanli** [comment]
document_code fixed https://github.com/barbaradanzo/birthdays/commit/ffb6341e99e3e0a0a84dbbbacbbc1a5fd6ca09ae
